default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default_local: &default_local
  <<: *default
  username: <%= ENV.fetch("POSTGRES_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  host: localhost

development:
  <<: *default_local
  database: mahnira_development

test:
  <<: *default_local
  database: mahnira_test

staging:
  <<: *default
  database: mahnira_staging
  username: mahnira_staging_user

default_production: &default_production
  <<: *default
  username: mahnira_user
  password: <%= ENV["MAHNIRA_DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

production:
  primary:
    <<: *default_production
    database: mahnira_production

  cable:
    <<: *default_production
    database: mahnira_production_cable
    migrations_paths: db/cable_migrate

  queue:
    <<: *default_production
    database: mahnira_production_queue
    migrations_paths: db/queue_migrate

  cache:
    <<: *default_production
    database: mahnira_production_cache
    migrations_paths: db/cache_migrate